# Generated by Django 5.1 on 2024-12-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('message', models.CharField(default='...', max_length=1200, verbose_name='mensagem')),
                ('created_at', models.DateTimeField(default=None, verbose_name='criado em')),
                ('answer', models.CharField(default='A ser respondido...', max_length=1200, verbose_name='answer')),
                ('answered_at', models.DateTimeField(default=None, verbose_name='respondido em')),
            ],
            options={
                'verbose_name': 'contactar',
                'verbose_name_plural': 'contactares',
            },
        ),
    ]
