# Generated by Django 5.1 on 2024-12-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contacts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='answered_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='respondido em'),
        ),
    ]
